find_package(PkgConfig REQUIRED QUIET)

macro(FIND_GSTREAMER_COMPONENT _component_prefix _pkgconfig_name _header _library)
	pkg_check_modules(PC_${_component_prefix} QUIET ${_pkgconfig_name})

	find_path(${_component_prefix}_INCLUDE_DIRS
		NAMES ${_header}
		HINTS ${PC_${_component_prefix}_INCLUDE_DIRS} ${PC_${_component_prefix}_INCLUDEDIR}
		PATH_SUFFIXES gstreamer-1.0
	)

	find_library(${_component_prefix}_LIBRARIES
		NAMES ${_library}
		HINTS ${PC_${_component_prefix}_LIBRARY_DIRS} ${PC_${_component_prefix}_LIBDIR}
	)
endmacro()

FIND_GSTREAMER_COMPONENT(GSTREAMER gstreamer-1.0 gst/gst.h gstreamer-1.0)
FIND_GSTREAMER_COMPONENT(GSTREAMER_CONFIG gstreamer-1.0 gst/gstconfig.h gstreamer-1.0)
FIND_GSTREAMER_COMPONENT(GSTREAMER_BASE gstreamer-base-1.0 gst/base/gstadapter.h gstbase-1.0)

if (GSTREAMER_INCLUDE_DIRS)
	if (EXISTS "${GSTREAMER_INCLUDE_DIRS}/gst/gstversion.h")
		file(READ "${GSTREAMER_INCLUDE_DIRS}/gst/gstversion.h" GSTREAMER_VERSION_CONTENTS)

		string(REGEX MATCH "#define +GST_VERSION_MAJOR +\\(([0-9]+)\\)" _dummy "${GSTREAMER_VERSION_CONTENTS}")
		set(GSTREAMER_VERSION_MAJOR "${CMAKE_MATCH_1}")

		string(REGEX MATCH "#define +GST_VERSION_MINOR +\\(([0-9]+)\\)" _dummy "${GSTREAMER_VERSION_CONTENTS}")
		set(GSTREAMER_VERSION_MINOR "${CMAKE_MATCH_1}")

		string(REGEX MATCH "#define +GST_VERSION_MICRO +\\(([0-9]+)\\)" _dummy "${GSTREAMER_VERSION_CONTENTS}")
		set(GSTREAMER_VERSION_MICRO "${CMAKE_MATCH_1}")

		set(GSTREAMER_VERSION "${GSTREAMER_VERSION_MAJOR}.${GSTREAMER_VERSION_MINOR}.${GSTREAMER_VERSION_MICRO}")
	endif ()
endif ()

if ("${GStreamer_FIND_VERSION}" VERSION_GREATER "${GSTREAMER_VERSION}")
	message(FATAL_ERROR "Required version (" ${GStreamer_FIND_VERSION} ") is higher than found version (" ${GSTREAMER_VERSION} ")")
endif ()

FIND_GSTREAMER_COMPONENT(GSTREAMER_APP gstreamer-app-1.0 gst/app/gstappsink.h gstapp-1.0)
FIND_GSTREAMER_COMPONENT(GSTREAMER_AUDIO gstreamer-audio-1.0 gst/audio/audio.h gstaudio-1.0)
FIND_GSTREAMER_COMPONENT(GSTREAMER_FFT gstreamer-fft-1.0 gst/fft/gstfft.h gstfft-1.0)
FIND_GSTREAMER_COMPONENT(GSTREAMER_MPEGTS gstreamer-mpegts-1.0>=1.4.0 gst/mpegts/mpegts.h gstmpegts-1.0)
FIND_GSTREAMER_COMPONENT(GSTREAMER_PBUTILS gstreamer-pbutils-1.0 gst/pbutils/pbutils.h gstpbutils-1.0)
FIND_GSTREAMER_COMPONENT(GSTREAMER_TAG gstreamer-tag-1.0 gst/tag/tag.h gsttag-1.0)
FIND_GSTREAMER_COMPONENT(GSTREAMER_VIDEO gstreamer-video-1.0 gst/video/video.h gstvideo-1.0)
FIND_GSTREAMER_COMPONENT(GSTREAMER_RTSPSERVER gstreamer-rtsp-1.0 gst/rtsp-server/rtsp-server.h gstrtspserver-1.0)

list(APPEND GSTREAMER_INCLUDE_DIRS ${GSTREAMER_CONFIG_INCLUDE_DIRS})
list(APPEND GSTREAMER_LIBRARIES ${GSTREAMER_CONFIG_LIBRARIES})

set(_GSTREAMER_REQUIRED_VARS GSTREAMER_INCLUDE_DIRS GSTREAMER_LIBRARIES GSTREAMER_VERSION GSTREAMER_BASE_INCLUDE_DIRS GSTREAMER_BASE_LIBRARIES)

foreach (_component ${GStreamer_FIND_COMPONENTS})
	set(_gst_component "GSTREAMER_${_component}")
	string(TOUPPER ${_gst_component} _UPPER_NAME)

	list(APPEND _GSTREAMER_REQUIRED_VARS ${_UPPER_NAME}_INCLUDE_DIRS ${_UPPER_NAME}_LIBRARIES)
endforeach ()

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GStreamer REQUIRED_VARS _GSTREAMER_REQUIRED_VARS
											VERSION_VAR   GSTREAMER_VERSION)

mark_as_advanced(
	GSTREAMER_APP_INCLUDE_DIRS
	GSTREAMER_APP_LIBRARIES
	GSTREAMER_AUDIO_INCLUDE_DIRS
	GSTREAMER_AUDIO_LIBRARIES
	GSTREAMER_BASE_INCLUDE_DIRS
	GSTREAMER_BASE_LIBRARIES
	GSTREAMER_CONFIG_INCLUDE_DIRS
	GSTREAMER_CONFIG_LIBRARIES
	GSTREAMER_FFT_INCLUDE_DIRS
	GSTREAMER_FFT_LIBRARIES
	GSTREAMER_INCLUDE_DIRS
	GSTREAMER_LIBRARIES
	GSTREAMER_MPEGTS_INCLUDE_DIRS
	GSTREAMER_MPEGTS_LIBRARIES
	GSTREAMER_PBUTILS_INCLUDE_DIRS
	GSTREAMER_PBUTILS_LIBRARIES
	GSTREAMER_TAG_INCLUDE_DIRS
	GSTREAMER_TAG_LIBRARIES
	GSTREAMER_VIDEO_INCLUDE_DIRS
	GSTREAMER_VIDEO_LIBRARIES
)

