#include <ros/ros.h> 
#include <surveillance_system/MotionEvent.h>
#include <sensor_msgs/Image>
#include <cv_bridge/cv_bridge.h>
#include <gst/gst.h>
#include <gst/app/gstappsrc.h>
#include <string>
#include <mutex>
#include <queue>